//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets3F5821C1B9D71AB0B99AA25BD6716F7093CA6FA02F4518058CCCB25A0AA99E0F))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets3F5821C1B9D71AB0B99AA25BD6716F7093CA6FA02F4518058CCCB25A0AA99E0F : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets3F5821C1B9D71AB0B99AA25BD6716F7093CA6FA02F4518058CCCB25A0AA99E0F()
        {
            this.EdmEntityContainerName = "AgrishareEntities";
            this.StoreEntityContainerName = "AgrishareModelStoreContainer";
            this.HashOverMappingClosure = "1766d79eda2b630c20f9167d242866cf23825a4fd6ab86017b673177d150b08b";
            this.HashOverAllExtentViews = "6fb4ddd07d5325483371cf767effcbd3b5126b682589caf176228a1da1b4042d";
            this.ViewCount = 32;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            if ((index == 22))
            {
                return GetView22();
            }
            if ((index == 23))
            {
                return GetView23();
            }
            if ((index == 24))
            {
                return GetView24();
            }
            if ((index == 25))
            {
                return GetView25();
            }
            if ((index == 26))
            {
                return GetView26();
            }
            if ((index == 27))
            {
                return GetView27();
            }
            if ((index == 28))
            {
                return GetView28();
            }
            if ((index == 29))
            {
                return GetView29();
            }
            if ((index == 30))
            {
                return GetView30();
            }
            if ((index == 31))
            {
                return GetView31();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Bookings
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2267);
            viewString.Append("\r\n    SELECT VALUE -- Constructing Bookings\r\n        [AgrishareModel.Store.Booki");
            viewString.Append("ngs](T1.Bookings_Id, T1.Bookings_ForId, T1.Bookings_UserId, T1.Bookings_ListingI");
            viewString.Append("d, T1.Bookings_ServiceId, T1.Bookings_Location, T1.Bookings_Latitude, T1.Booking");
            viewString.Append("s_Longitude, T1.Bookings_Destination, T1.Bookings_DestinationLatitude, T1.Bookin");
            viewString.Append("gs_DestinationLongitude, T1.Bookings_Quantity, T1.Bookings_Distance, T1.Bookings");
            viewString.Append("_IncludeFuel, T1.Bookings_StartDate, T1.Bookings_EndDate, T1.Bookings_Price, T1.");
            viewString.Append("Bookings_HireCost, T1.Bookings_FuelCost, T1.Bookings_TransportCost, T1.Bookings_");
            viewString.Append("TransportDistance, T1.Bookings_AdditionalInformation, T1.Bookings_TotalVolume, T");
            viewString.Append("1.Bookings_StatusId, T1.Bookings_DateCreated, T1.Bookings_LastModified, T1.Booki");
            viewString.Append("ngs_Deleted)\r\n    FROM (\r\n        SELECT \r\n            T.Id AS Bookings_Id, \r\n  ");
            viewString.Append("          CAST(T.ForId AS [Edm.Int16]) AS Bookings_ForId, \r\n            T.UserId");
            viewString.Append(" AS Bookings_UserId, \r\n            T.ListingId AS Bookings_ListingId, \r\n        ");
            viewString.Append("    T.ServiceId AS Bookings_ServiceId, \r\n            T.Location AS Bookings_Loca");
            viewString.Append("tion, \r\n            T.Latitude AS Bookings_Latitude, \r\n            T.Longitude A");
            viewString.Append("S Bookings_Longitude, \r\n            T.Destination AS Bookings_Destination, \r\n   ");
            viewString.Append("         T.DestinationLatitude AS Bookings_DestinationLatitude, \r\n            T.");
            viewString.Append("DestinationLongitude AS Bookings_DestinationLongitude, \r\n            T.Quantity ");
            viewString.Append("AS Bookings_Quantity, \r\n            T.Distance AS Bookings_Distance, \r\n         ");
            viewString.Append("   T.IncludeFuel AS Bookings_IncludeFuel, \r\n            T.StartDate AS Bookings_");
            viewString.Append("StartDate, \r\n            T.EndDate AS Bookings_EndDate, \r\n            T.Price AS");
            viewString.Append(" Bookings_Price, \r\n            T.HireCost AS Bookings_HireCost, \r\n            T.");
            viewString.Append("FuelCost AS Bookings_FuelCost, \r\n            T.TransportCost AS Bookings_Transpo");
            viewString.Append("rtCost, \r\n            T.TransportDistance AS Bookings_TransportDistance, \r\n     ");
            viewString.Append("       T.AdditionalInformation AS Bookings_AdditionalInformation, \r\n            ");
            viewString.Append("T.TotalVolume AS Bookings_TotalVolume, \r\n            CAST(T.StatusId AS [Edm.Int");
            viewString.Append("16]) AS Bookings_StatusId, \r\n            T.DateCreated AS Bookings_DateCreated, ");
            viewString.Append("\r\n            T.LastModified AS Bookings_LastModified, \r\n            T.Deleted A");
            viewString.Append("S Bookings_Deleted, \r\n            True AS _from0\r\n        FROM AgrishareEntities");
            viewString.Append(".Bookings AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Bookings", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.BookingUsers
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.BookingUsers", @"
    SELECT VALUE -- Constructing BookingUsers
        [AgrishareModel.Store.BookingUsers](T1.BookingUsers_Id, T1.BookingUsers_BookingId, T1.BookingUsers_UserId, T1.BookingUsers_Name, T1.BookingUsers_Telephone, T1.BookingUsers_Ratio, T1.BookingUsers_VerificationCode, T1.BookingUsers_VerificationCodeExpiry, T1.BookingUsers_StatusId, T1.BookingUsers_DateCreated, T1.BookingUsers_LastModified, T1.BookingUsers_Deleted)
    FROM (
        SELECT 
            T.Id AS BookingUsers_Id, 
            T.BookingId AS BookingUsers_BookingId, 
            T.UserId AS BookingUsers_UserId, 
            T.Name AS BookingUsers_Name, 
            T.Telephone AS BookingUsers_Telephone, 
            T.Ratio AS BookingUsers_Ratio, 
            T.VerificationCode AS BookingUsers_VerificationCode, 
            T.VerificationCodeExpiry AS BookingUsers_VerificationCodeExpiry, 
            CAST(T.StatusId AS [Edm.Int16]) AS BookingUsers_StatusId, 
            T.DateCreated AS BookingUsers_DateCreated, 
            T.LastModified AS BookingUsers_LastModified, 
            T.Deleted AS BookingUsers_Deleted, 
            True AS _from0
        FROM AgrishareEntities.BookingUsers AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Categories
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Categories", @"
    SELECT VALUE -- Constructing Categories
        [AgrishareModel.Store.Categories](T1.Categories_Id, T1.Categories_ParentId, T1.Categories_Title, T1.Categories_DateCreated, T1.Categories_LastModified, T1.Categories_Deleted)
    FROM (
        SELECT 
            T.Id AS Categories_Id, 
            T.ParentId AS Categories_ParentId, 
            T.Title AS Categories_Title, 
            T.DateCreated AS Categories_DateCreated, 
            T.LastModified AS Categories_LastModified, 
            T.Deleted AS Categories_Deleted, 
            True AS _from0
        FROM AgrishareEntities.Categories AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Listings
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Listings", "\r\n    SELECT VALUE -- Constructing Listings\r\n        [AgrishareModel.Store.Listin" +
                    "gs](T1.Listings_Id, T1.Listings_UserId, T1.Listings_CategoryId, T1.Listings_Titl" +
                    "e, T1.Listings_Description, T1.Listings_Location, T1.Listings_Latitude, T1.Listi" +
                    "ngs_Longitude, T1.Listings_Brand, T1.Listings_HorsePower, T1.Listings_Year, T1.L" +
                    "istings_ConditionId, T1.Listings_GroupServices, T1.Listings_Photos, T1.Listings_" +
                    "AvailableWithoutFuel, T1.Listings_AvailableWithFuel, T1.Listings_AverageRating, " +
                    "T1.Listings_RatingCount, T1.Listings_StatusId, T1.Listings_DateCreated, T1.Listi" +
                    "ngs_LastModified, T1.Listings_Deleted)\r\n    FROM (\r\n        SELECT \r\n           " +
                    " T.Id AS Listings_Id, \r\n            T.UserId AS Listings_UserId, \r\n            T" +
                    ".CategoryId AS Listings_CategoryId, \r\n            T.Title AS Listings_Title, \r\n " +
                    "           T.Description AS Listings_Description, \r\n            T.Location AS Li" +
                    "stings_Location, \r\n            T.Latitude AS Listings_Latitude, \r\n            T." +
                    "Longitude AS Listings_Longitude, \r\n            T.Brand AS Listings_Brand, \r\n    " +
                    "        T.HorsePower AS Listings_HorsePower, \r\n            T.Year AS Listings_Ye" +
                    "ar, \r\n            CAST(T.ConditionId AS [Edm.Int16]) AS Listings_ConditionId, \r\n" +
                    "            T.GroupServices AS Listings_GroupServices, \r\n            T.PhotoPath" +
                    "s AS Listings_Photos, \r\n            T.AvailableWithoutFuel AS Listings_Available" +
                    "WithoutFuel, \r\n            T.AvailableWithFuel AS Listings_AvailableWithFuel, \r\n" +
                    "            T.AverageRating AS Listings_AverageRating, \r\n            T.RatingCou" +
                    "nt AS Listings_RatingCount, \r\n            CAST(T.StatusId AS [Edm.Int16]) AS Lis" +
                    "tings_StatusId, \r\n            T.DateCreated AS Listings_DateCreated, \r\n         " +
                    "   T.LastModified AS Listings_LastModified, \r\n            T.Deleted AS Listings_" +
                    "Deleted, \r\n            True AS _from0\r\n        FROM AgrishareEntities.Listings A" +
                    "S T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Notifications
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Notifications", @"
    SELECT VALUE -- Constructing Notifications
        [AgrishareModel.Store.Notifications](T1.Notifications_Id, T1.Notifications_UserId, T1.Notifications_BookingId, T1.Notifications_TypeId, T1.Notifications_StatusId, T1.Notifications_GroupId, T1.Notifications_Message, T1.Notifications_DateCreated, T1.Notifications_LastModified, T1.Notifications_Deleted)
    FROM (
        SELECT 
            T.Id AS Notifications_Id, 
            T.UserId AS Notifications_UserId, 
            T.BookingId AS Notifications_BookingId, 
            CAST(T.TypeId AS [Edm.Int16]) AS Notifications_TypeId, 
            CAST(T.StatusId AS [Edm.Int16]) AS Notifications_StatusId, 
            CAST(T.GroupId AS [Edm.Int16]) AS Notifications_GroupId, 
            T.Message AS Notifications_Message, 
            T.DateCreated AS Notifications_DateCreated, 
            T.LastModified AS Notifications_LastModified, 
            T.Deleted AS Notifications_Deleted, 
            True AS _from0
        FROM AgrishareEntities.Notifications AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Transactions
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Transactions", @"
    SELECT VALUE -- Constructing Transactions
        [AgrishareModel.Store.Transactions](T1.Transactions_Id, T1.Transactions_ClientCorrelator, T1.Transactions_BookingId, T1.Transactions_BookingUserId, T1.Transactions_Reference, T1.Transactions_Amount, T1.Transactions_StatusId, T1.Transactions_Log, T1.Transactions_Error, T1.Transactions_DateCreated, T1.Transactions_LastModified, T1.Transactions_Deleted)
    FROM (
        SELECT 
            T.Id AS Transactions_Id, 
            T.ClientCorrelator AS Transactions_ClientCorrelator, 
            T.BookingId AS Transactions_BookingId, 
            T.BookingUserId AS Transactions_BookingUserId, 
            T.Reference AS Transactions_Reference, 
            T.Amount AS Transactions_Amount, 
            CAST(T.StatusId AS [Edm.Int16]) AS Transactions_StatusId, 
            T.Log AS Transactions_Log, 
            T.Error AS Transactions_Error, 
            T.DateCreated AS Transactions_DateCreated, 
            T.LastModified AS Transactions_LastModified, 
            T.Deleted AS Transactions_Deleted, 
            True AS _from0
        FROM AgrishareEntities.Transactions AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Users
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Users", "\r\n    SELECT VALUE -- Constructing Users\r\n        [AgrishareModel.Store.Users](T1" +
                    ".Users_Id, T1.Users_FirstName, T1.Users_LastName, T1.Users_EmailAddress, T1.User" +
                    "s_Telephone, T1.Users_GenderId, T1.Users_DateOfBirth, T1.Users_Password, T1.User" +
                    "s_Salt, T1.Users_AuthToken, T1.Users_FailedLoginAttempts, T1.Users_VerificationC" +
                    "ode, T1.Users_VerificationCodeExpiry, T1.Users_NotificationPreferences, T1.Users" +
                    "_InterestId, T1.Users_SignalRConnectionId, T1.Users_StatusId, T1.Users_RoleList," +
                    " T1.Users_DateCreated, T1.Users_LastModified, T1.Users_Deleted)\r\n    FROM (\r\n   " +
                    "     SELECT \r\n            T.Id AS Users_Id, \r\n            T.FirstName AS Users_F" +
                    "irstName, \r\n            T.LastName AS Users_LastName, \r\n            T.EmailAddre" +
                    "ss AS Users_EmailAddress, \r\n            T.Telephone AS Users_Telephone, \r\n      " +
                    "      CAST(T.GenderId AS [Edm.Int16]) AS Users_GenderId, \r\n            T.DateOfB" +
                    "irth AS Users_DateOfBirth, \r\n            T.Password AS Users_Password, \r\n       " +
                    "     T.Salt AS Users_Salt, \r\n            T.AuthToken AS Users_AuthToken, \r\n     " +
                    "       T.FailedLoginAttempts AS Users_FailedLoginAttempts, \r\n            T.Verif" +
                    "icationCode AS Users_VerificationCode, \r\n            T.VerificationCodeExpiry AS" +
                    " Users_VerificationCodeExpiry, \r\n            T.NotificationPreferences AS Users_" +
                    "NotificationPreferences, \r\n            CAST(T.InterestId AS [Edm.Int16]) AS User" +
                    "s_InterestId, \r\n            T.SignalRConnectionId AS Users_SignalRConnectionId, " +
                    "\r\n            CAST(T.StatusId AS [Edm.Int16]) AS Users_StatusId, \r\n            T" +
                    ".RoleList AS Users_RoleList, \r\n            T.DateCreated AS Users_DateCreated, \r" +
                    "\n            T.LastModified AS Users_LastModified, \r\n            T.Deleted AS Us" +
                    "ers_Deleted, \r\n            True AS _from0\r\n        FROM AgrishareEntities.Users " +
                    "AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Ratings
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Ratings", @"
    SELECT VALUE -- Constructing Ratings
        [AgrishareModel.Store.Ratings](T1.Ratings_Id, T1.Ratings_ListingId, T1.Ratings_UserId, T1.Ratings_Comments, T1.Ratings_Rating, T1.Ratings_DateCreated, T1.Ratings_LastModified, T1.Ratings_Deleted)
    FROM (
        SELECT 
            T.Id AS Ratings_Id, 
            T.ListingId AS Ratings_ListingId, 
            T.UserId AS Ratings_UserId, 
            T.Comments AS Ratings_Comments, 
            T.Stars AS Ratings_Rating, 
            T.DateCreated AS Ratings_DateCreated, 
            T.LastModified AS Ratings_LastModified, 
            T.Deleted AS Ratings_Deleted, 
            True AS _from0
        FROM AgrishareEntities.Ratings AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Services
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Services", "\r\n    SELECT VALUE -- Constructing Services\r\n        [AgrishareModel.Store.Servic" +
                    "es](T1.Services_Id, T1.Services_ListingId, T1.Services_CategoryId, T1.Services_M" +
                    "obile, T1.Services_TotalVolume, T1.Services_QuantityUnitId, T1.Services_TimeUnit" +
                    "Id, T1.Services_DistanceUnitId, T1.Services_MinimumQuantity, T1.Services_Maximum" +
                    "Distance, T1.Services_PricePerQuantityUnit, T1.Services_FuelPerQuantityUnit, T1." +
                    "Services_TimePerQuantityUnit, T1.Services_PricePerDistanceUnit, T1.Services_Fuel" +
                    "Price, T1.Services_DateCreated, T1.Services_LastModified, T1.Services_Deleted)\r\n" +
                    "    FROM (\r\n        SELECT \r\n            T.Id AS Services_Id, \r\n            T.Li" +
                    "stingId AS Services_ListingId, \r\n            T.CategoryId AS Services_CategoryId" +
                    ", \r\n            T.Mobile AS Services_Mobile, \r\n            T.TotalVolume AS Serv" +
                    "ices_TotalVolume, \r\n            CAST(T.QuantityUnitId AS [Edm.Int16]) AS Service" +
                    "s_QuantityUnitId, \r\n            CAST(T.TimeUnitId AS [Edm.Int16]) AS Services_Ti" +
                    "meUnitId, \r\n            CAST(T.DistanceUnitId AS [Edm.Int16]) AS Services_Distan" +
                    "ceUnitId, \r\n            T.MinimumQuantity AS Services_MinimumQuantity, \r\n       " +
                    "     T.MaximumDistance AS Services_MaximumDistance, \r\n            T.PricePerQuan" +
                    "tityUnit AS Services_PricePerQuantityUnit, \r\n            T.FuelPerQuantityUnit A" +
                    "S Services_FuelPerQuantityUnit, \r\n            T.TimePerQuantityUnit AS Services_" +
                    "TimePerQuantityUnit, \r\n            T.PricePerDistanceUnit AS Services_PricePerDi" +
                    "stanceUnit, \r\n            T.FuelPrice AS Services_FuelPrice, \r\n            T.Dat" +
                    "eCreated AS Services_DateCreated, \r\n            T.LastModified AS Services_LastM" +
                    "odified, \r\n            T.Deleted AS Services_Deleted, \r\n            True AS _fro" +
                    "m0\r\n        FROM AgrishareEntities.Services AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Counters
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Counters", @"
    SELECT VALUE -- Constructing Counters
        [AgrishareModel.Store.Counters](T1.Counters_Id, T1.Counters_UserId, T1.Counters_ServiceId, T1.Counters_Event, T1.Counters_DateCreated, T1.Counters_LastModified, T1.Counters_Deleted)
    FROM (
        SELECT 
            T.Id AS Counters_Id, 
            T.UserId AS Counters_UserId, 
            T.ServiceId AS Counters_ServiceId, 
            T.Event AS Counters_Event, 
            T.DateCreated AS Counters_DateCreated, 
            T.LastModified AS Counters_LastModified, 
            T.Deleted AS Counters_Deleted, 
            True AS _from0
        FROM AgrishareEntities.Counters AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Devices
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Devices", @"
    SELECT VALUE -- Constructing Devices
        [AgrishareModel.Store.Devices](T1.Devices_Id, T1.Devices_UserId, T1.Devices_Token, T1.Devices_EndpointARN, T1.Devices_DateCreated, T1.Devices_LastModified, T1.Devices_Deleted)
    FROM (
        SELECT 
            T.Id AS Devices_Id, 
            T.UserId AS Devices_UserId, 
            T.Token AS Devices_Token, 
            T.EndpointARN AS Devices_EndpointARN, 
            T.DateCreated AS Devices_DateCreated, 
            T.LastModified AS Devices_LastModified, 
            T.Deleted AS Devices_Deleted, 
            True AS _from0
        FROM AgrishareEntities.Devices AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Bookings
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2252);
            viewString.Append("\r\n    SELECT VALUE -- Constructing Bookings\r\n        [AgrishareModel.Booking](T1");
            viewString.Append(".Booking_Id, T1.Booking_ListingId, T1.Booking_ServiceId, T1.Booking_ForId, T1.Bo");
            viewString.Append("oking_UserId, T1.Booking_Location, T1.Booking_Latitude, T1.Booking_Longitude, T1");
            viewString.Append(".Booking_Quantity, T1.Booking_Distance, T1.Booking_IncludeFuel, T1.Booking_Start");
            viewString.Append("Date, T1.Booking_EndDate, T1.Booking_Price, T1.Booking_HireCost, T1.Booking_Fuel");
            viewString.Append("Cost, T1.Booking_TransportCost, T1.Booking_StatusId, T1.Booking_DateCreated, T1.");
            viewString.Append("Booking_LastModified, T1.Booking_Deleted, T1.Booking_DestinationLatitude, T1.Boo");
            viewString.Append("king_DestinationLongitude, T1.Booking_Destination, T1.Booking_AdditionalInformat");
            viewString.Append("ion, T1.Booking_TotalVolume, T1.Booking_TransportDistance)\r\n    FROM (\r\n        ");
            viewString.Append("SELECT \r\n            T.Id AS Booking_Id, \r\n            T.ListingId AS Booking_Li");
            viewString.Append("stingId, \r\n            T.ServiceId AS Booking_ServiceId, \r\n            CAST(T.Fo");
            viewString.Append("rId AS [AgrishareModel.BookingFor]) AS Booking_ForId, \r\n            T.UserId AS ");
            viewString.Append("Booking_UserId, \r\n            T.Location AS Booking_Location, \r\n            T.La");
            viewString.Append("titude AS Booking_Latitude, \r\n            T.Longitude AS Booking_Longitude, \r\n  ");
            viewString.Append("          T.Quantity AS Booking_Quantity, \r\n            T.Distance AS Booking_Di");
            viewString.Append("stance, \r\n            T.IncludeFuel AS Booking_IncludeFuel, \r\n            T.Star");
            viewString.Append("tDate AS Booking_StartDate, \r\n            T.EndDate AS Booking_EndDate, \r\n      ");
            viewString.Append("      T.Price AS Booking_Price, \r\n            T.HireCost AS Booking_HireCost, \r\n");
            viewString.Append("            T.FuelCost AS Booking_FuelCost, \r\n            T.TransportCost AS Boo");
            viewString.Append("king_TransportCost, \r\n            CAST(T.StatusId AS [AgrishareModel.BookingStat");
            viewString.Append("us]) AS Booking_StatusId, \r\n            T.DateCreated AS Booking_DateCreated, \r\n");
            viewString.Append("            T.LastModified AS Booking_LastModified, \r\n            T.Deleted AS B");
            viewString.Append("ooking_Deleted, \r\n            T.DestinationLatitude AS Booking_DestinationLatitu");
            viewString.Append("de, \r\n            T.DestinationLongitude AS Booking_DestinationLongitude, \r\n    ");
            viewString.Append("        T.Destination AS Booking_Destination, \r\n            T.AdditionalInformat");
            viewString.Append("ion AS Booking_AdditionalInformation, \r\n            T.TotalVolume AS Booking_Tot");
            viewString.Append("alVolume, \r\n            T.TransportDistance AS Booking_TransportDistance, \r\n    ");
            viewString.Append("        True AS _from0\r\n        FROM AgrishareModelStoreContainer.Bookings AS T\r");
            viewString.Append("\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Bookings", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.BookingUsers
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.BookingUsers", @"
    SELECT VALUE -- Constructing BookingUsers
        [AgrishareModel.BookingUser](T1.BookingUser_Id, T1.BookingUser_BookingId, T1.BookingUser_UserId, T1.BookingUser_Name, T1.BookingUser_Telephone, T1.BookingUser_Ratio, T1.BookingUser_VerificationCode, T1.BookingUser_VerificationCodeExpiry, T1.BookingUser_StatusId, T1.BookingUser_DateCreated, T1.BookingUser_LastModified, T1.BookingUser_Deleted)
    FROM (
        SELECT 
            T.Id AS BookingUser_Id, 
            T.BookingId AS BookingUser_BookingId, 
            T.UserId AS BookingUser_UserId, 
            T.Name AS BookingUser_Name, 
            T.Telephone AS BookingUser_Telephone, 
            T.Ratio AS BookingUser_Ratio, 
            T.VerificationCode AS BookingUser_VerificationCode, 
            T.VerificationCodeExpiry AS BookingUser_VerificationCodeExpiry, 
            CAST(T.StatusId AS [AgrishareModel.BookingUserStatus]) AS BookingUser_StatusId, 
            T.DateCreated AS BookingUser_DateCreated, 
            T.LastModified AS BookingUser_LastModified, 
            T.Deleted AS BookingUser_Deleted, 
            True AS _from0
        FROM AgrishareModelStoreContainer.BookingUsers AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Categories
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Categories", @"
    SELECT VALUE -- Constructing Categories
        [AgrishareModel.Category](T1.Category_Id, T1.Category_ParentId, T1.Category_Title, T1.Category_DateCreated, T1.Category_LastModified, T1.Category_Deleted)
    FROM (
        SELECT 
            T.Id AS Category_Id, 
            T.ParentId AS Category_ParentId, 
            T.Title AS Category_Title, 
            T.DateCreated AS Category_DateCreated, 
            T.LastModified AS Category_LastModified, 
            T.Deleted AS Category_Deleted, 
            True AS _from0
        FROM AgrishareModelStoreContainer.Categories AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Listings
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Listings", "\r\n    SELECT VALUE -- Constructing Listings\r\n        [AgrishareModel.Listing](T1." +
                    "Listing_Id, T1.Listing_UserId, T1.Listing_CategoryId, T1.Listing_Title, T1.Listi" +
                    "ng_Description, T1.Listing_AverageRating, T1.Listing_RatingCount, T1.Listing_Loc" +
                    "ation, T1.Listing_Latitude, T1.Listing_Longitude, T1.Listing_Brand, T1.Listing_H" +
                    "orsePower, T1.Listing_Year, T1.Listing_AvailableWithoutFuel, T1.Listing_Availabl" +
                    "eWithFuel, T1.Listing_ConditionId, T1.Listing_GroupServices, T1.Listing_PhotoPat" +
                    "hs, T1.Listing_StatusId, T1.Listing_DateCreated, T1.Listing_LastModified, T1.Lis" +
                    "ting_Deleted)\r\n    FROM (\r\n        SELECT \r\n            T.Id AS Listing_Id, \r\n  " +
                    "          T.UserId AS Listing_UserId, \r\n            T.CategoryId AS Listing_Cate" +
                    "goryId, \r\n            T.Title AS Listing_Title, \r\n            T.Description AS L" +
                    "isting_Description, \r\n            T.AverageRating AS Listing_AverageRating, \r\n  " +
                    "          T.RatingCount AS Listing_RatingCount, \r\n            T.Location AS List" +
                    "ing_Location, \r\n            T.Latitude AS Listing_Latitude, \r\n            T.Long" +
                    "itude AS Listing_Longitude, \r\n            T.Brand AS Listing_Brand, \r\n          " +
                    "  T.HorsePower AS Listing_HorsePower, \r\n            T.Year AS Listing_Year, \r\n  " +
                    "          T.AvailableWithoutFuel AS Listing_AvailableWithoutFuel, \r\n            " +
                    "T.AvailableWithFuel AS Listing_AvailableWithFuel, \r\n            CAST(T.Condition" +
                    "Id AS [AgrishareModel.ListingCondition]) AS Listing_ConditionId, \r\n            T" +
                    ".GroupServices AS Listing_GroupServices, \r\n            T.Photos AS Listing_Photo" +
                    "Paths, \r\n            CAST(T.StatusId AS [AgrishareModel.ListingStatus]) AS Listi" +
                    "ng_StatusId, \r\n            T.DateCreated AS Listing_DateCreated, \r\n            T" +
                    ".LastModified AS Listing_LastModified, \r\n            T.Deleted AS Listing_Delete" +
                    "d, \r\n            True AS _from0\r\n        FROM AgrishareModelStoreContainer.Listi" +
                    "ngs AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Notifications
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Notifications", @"
    SELECT VALUE -- Constructing Notifications
        [AgrishareModel.Notification](T1.Notification_Id, T1.Notification_UserId, T1.Notification_BookingId, T1.Notification_TypeId, T1.Notification_StatusId, T1.Notification_GroupId, T1.Notification_DateCreated, T1.Notification_LastModified, T1.Notification_Deleted, T1.Notification_Message)
    FROM (
        SELECT 
            T.Id AS Notification_Id, 
            T.UserId AS Notification_UserId, 
            T.BookingId AS Notification_BookingId, 
            CAST(T.TypeId AS [AgrishareModel.NotificationType]) AS Notification_TypeId, 
            CAST(T.StatusId AS [AgrishareModel.NotificationStatus]) AS Notification_StatusId, 
            CAST(T.GroupId AS [AgrishareModel.NotificationGroup]) AS Notification_GroupId, 
            T.DateCreated AS Notification_DateCreated, 
            T.LastModified AS Notification_LastModified, 
            T.Deleted AS Notification_Deleted, 
            T.Message AS Notification_Message, 
            True AS _from0
        FROM AgrishareModelStoreContainer.Notifications AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Transactions
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Transactions", @"
    SELECT VALUE -- Constructing Transactions
        [AgrishareModel.Transaction](T1.Transaction_Id, T1.Transaction_ClientCorrelator, T1.Transaction_BookingId, T1.Transaction_BookingUserId, T1.Transaction_Reference, T1.Transaction_Amount, T1.Transaction_StatusId, T1.Transaction_Log, T1.Transaction_Error, T1.Transaction_DateCreated, T1.Transaction_LastModified, T1.Transaction_Deleted)
    FROM (
        SELECT 
            T.Id AS Transaction_Id, 
            T.ClientCorrelator AS Transaction_ClientCorrelator, 
            T.BookingId AS Transaction_BookingId, 
            T.BookingUserId AS Transaction_BookingUserId, 
            T.Reference AS Transaction_Reference, 
            T.Amount AS Transaction_Amount, 
            CAST(T.StatusId AS [AgrishareModel.TransactionStatus]) AS Transaction_StatusId, 
            T.Log AS Transaction_Log, 
            T.Error AS Transaction_Error, 
            T.DateCreated AS Transaction_DateCreated, 
            T.LastModified AS Transaction_LastModified, 
            T.Deleted AS Transaction_Deleted, 
            True AS _from0
        FROM AgrishareModelStoreContainer.Transactions AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Users
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Users", "\r\n    SELECT VALUE -- Constructing Users\r\n        [AgrishareModel.User](T1.User_I" +
                    "d, T1.User_FirstName, T1.User_LastName, T1.User_EmailAddress, T1.User_Telephone," +
                    " T1.User_GenderId, T1.User_DateOfBirth, T1.User_NotificationPreferences, T1.User" +
                    "_InterestId, T1.User_RoleList, T1.User_Password, T1.User_Salt, T1.User_AuthToken" +
                    ", T1.User_FailedLoginAttempts, T1.User_VerificationCode, T1.User_VerificationCod" +
                    "eExpiry, T1.User_SignalRConnectionId, T1.User_StatusId, T1.User_DateCreated, T1." +
                    "User_LastModified, T1.User_Deleted)\r\n    FROM (\r\n        SELECT \r\n            T." +
                    "Id AS User_Id, \r\n            T.FirstName AS User_FirstName, \r\n            T.Last" +
                    "Name AS User_LastName, \r\n            T.EmailAddress AS User_EmailAddress, \r\n    " +
                    "        T.Telephone AS User_Telephone, \r\n            CAST(T.GenderId AS [Agrisha" +
                    "reModel.Gender]) AS User_GenderId, \r\n            T.DateOfBirth AS User_DateOfBir" +
                    "th, \r\n            T.NotificationPreferences AS User_NotificationPreferences, \r\n " +
                    "           CAST(T.InterestId AS [AgrishareModel.Interest]) AS User_InterestId, \r" +
                    "\n            T.RoleList AS User_RoleList, \r\n            T.Password AS User_Passw" +
                    "ord, \r\n            T.Salt AS User_Salt, \r\n            T.AuthToken AS User_AuthTo" +
                    "ken, \r\n            T.FailedLoginAttempts AS User_FailedLoginAttempts, \r\n        " +
                    "    T.VerificationCode AS User_VerificationCode, \r\n            T.VerificationCod" +
                    "eExpiry AS User_VerificationCodeExpiry, \r\n            T.SignalRConnectionId AS U" +
                    "ser_SignalRConnectionId, \r\n            CAST(T.StatusId AS [AgrishareModel.UserSt" +
                    "atus]) AS User_StatusId, \r\n            T.DateCreated AS User_DateCreated, \r\n    " +
                    "        T.LastModified AS User_LastModified, \r\n            T.Deleted AS User_Del" +
                    "eted, \r\n            True AS _from0\r\n        FROM AgrishareModelStoreContainer.Us" +
                    "ers AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Ratings
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Ratings", @"
    SELECT VALUE -- Constructing Ratings
        [AgrishareModel.Rating](T1.Rating_Id, T1.Rating_ListingId, T1.Rating_UserId, T1.Rating_Comments, T1.Rating_Stars, T1.Rating_DateCreated, T1.Rating_LastModified, T1.Rating_Deleted)
    FROM (
        SELECT 
            T.Id AS Rating_Id, 
            T.ListingId AS Rating_ListingId, 
            T.UserId AS Rating_UserId, 
            T.Comments AS Rating_Comments, 
            T.Rating AS Rating_Stars, 
            T.DateCreated AS Rating_DateCreated, 
            T.LastModified AS Rating_LastModified, 
            T.Deleted AS Rating_Deleted, 
            True AS _from0
        FROM AgrishareModelStoreContainer.Ratings AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Services
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Services", "\r\n    SELECT VALUE -- Constructing Services\r\n        [AgrishareModel.Service](T1." +
                    "Service_Id, T1.Service_ListingId, T1.Service_CategoryId, T1.Service_Mobile, T1.S" +
                    "ervice_TotalVolume, T1.Service_QuantityUnitId, T1.Service_TimeUnitId, T1.Service" +
                    "_DistanceUnitId, T1.Service_MinimumQuantity, T1.Service_MaximumDistance, T1.Serv" +
                    "ice_PricePerQuantityUnit, T1.Service_FuelPerQuantityUnit, T1.Service_TimePerQuan" +
                    "tityUnit, T1.Service_PricePerDistanceUnit, T1.Service_FuelPrice, T1.Service_Date" +
                    "Created, T1.Service_LastModified, T1.Service_Deleted)\r\n    FROM (\r\n        SELEC" +
                    "T \r\n            T.Id AS Service_Id, \r\n            T.ListingId AS Service_Listing" +
                    "Id, \r\n            T.CategoryId AS Service_CategoryId, \r\n            T.Mobile AS " +
                    "Service_Mobile, \r\n            T.TotalVolume AS Service_TotalVolume, \r\n          " +
                    "  CAST(T.QuantityUnitId AS [AgrishareModel.QuantityUnit]) AS Service_QuantityUni" +
                    "tId, \r\n            CAST(T.TimeUnitId AS [AgrishareModel.TimeUnit]) AS Service_Ti" +
                    "meUnitId, \r\n            CAST(T.DistanceUnitId AS [AgrishareModel.DistanceUnit]) " +
                    "AS Service_DistanceUnitId, \r\n            T.MinimumQuantity AS Service_MinimumQua" +
                    "ntity, \r\n            T.MaximumDistance AS Service_MaximumDistance, \r\n           " +
                    " T.PricePerQuantityUnit AS Service_PricePerQuantityUnit, \r\n            T.FuelPer" +
                    "QuantityUnit AS Service_FuelPerQuantityUnit, \r\n            T.TimePerQuantityUnit" +
                    " AS Service_TimePerQuantityUnit, \r\n            T.PricePerDistanceUnit AS Service" +
                    "_PricePerDistanceUnit, \r\n            T.FuelPrice AS Service_FuelPrice, \r\n       " +
                    "     T.DateCreated AS Service_DateCreated, \r\n            T.LastModified AS Servi" +
                    "ce_LastModified, \r\n            T.Deleted AS Service_Deleted, \r\n            True " +
                    "AS _from0\r\n        FROM AgrishareModelStoreContainer.Services AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Counters
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Counters", @"
    SELECT VALUE -- Constructing Counters
        [AgrishareModel.Counter](T1.Counter_Id, T1.Counter_UserId, T1.Counter_ServiceId, T1.Counter_Event, T1.Counter_DateCreated, T1.Counter_LastModified, T1.Counter_Deleted)
    FROM (
        SELECT 
            T.Id AS Counter_Id, 
            T.UserId AS Counter_UserId, 
            T.ServiceId AS Counter_ServiceId, 
            T.Event AS Counter_Event, 
            T.DateCreated AS Counter_DateCreated, 
            T.LastModified AS Counter_LastModified, 
            T.Deleted AS Counter_Deleted, 
            True AS _from0
        FROM AgrishareModelStoreContainer.Counters AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Devices
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Devices", @"
    SELECT VALUE -- Constructing Devices
        [AgrishareModel.Device](T1.Device_Id, T1.Device_UserId, T1.Device_Token, T1.Device_EndpointARN, T1.Device_DateCreated, T1.Device_LastModified, T1.Device_Deleted)
    FROM (
        SELECT 
            T.Id AS Device_Id, 
            T.UserId AS Device_UserId, 
            T.Token AS Device_Token, 
            T.EndpointARN AS Device_EndpointARN, 
            T.DateCreated AS Device_DateCreated, 
            T.LastModified AS Device_LastModified, 
            T.Deleted AS Device_Deleted, 
            True AS _from0
        FROM AgrishareModelStoreContainer.Devices AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Config
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView22()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Config", @"
    SELECT VALUE -- Constructing Config
        [AgrishareModel.Store.Config](T1.Config_Id, T1.Config_Key, T1.Config_Value, T1.Config_DateCreated, T1.Config_LastModified, T1.Config_Deleted)
    FROM (
        SELECT 
            T.Id AS Config_Id, 
            T.[Key] AS Config_Key, 
            T.[Value] AS Config_Value, 
            T.DateCreated AS Config_DateCreated, 
            T.LastModified AS Config_LastModified, 
            T.Deleted AS Config_Deleted, 
            True AS _from0
        FROM AgrishareEntities.Configs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Configs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView23()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Configs", @"
    SELECT VALUE -- Constructing Configs
        [AgrishareModel.Config](T1.Config_Id, T1.Config_Key, T1.Config_Value, T1.Config_DateCreated, T1.Config_LastModified, T1.Config_Deleted)
    FROM (
        SELECT 
            T.Id AS Config_Id, 
            T.[Key] AS Config_Key, 
            T.[Value] AS Config_Value, 
            T.DateCreated AS Config_DateCreated, 
            T.LastModified AS Config_LastModified, 
            T.Deleted AS Config_Deleted, 
            True AS _from0
        FROM AgrishareModelStoreContainer.Config AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Faqs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView24()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Faqs", @"
    SELECT VALUE -- Constructing Faqs
        [AgrishareModel.Store.Faqs](T1.Faqs_Id, T1.Faqs_Question, T1.Faqs_Answer, T1.Faqs_SortOrder, T1.Faqs_DateCreated, T1.Faqs_LastModified, T1.Faqs_Deleted)
    FROM (
        SELECT 
            T.Id AS Faqs_Id, 
            T.Question AS Faqs_Question, 
            T.Answer AS Faqs_Answer, 
            T.SortOrder AS Faqs_SortOrder, 
            T.DateCreated AS Faqs_DateCreated, 
            T.LastModified AS Faqs_LastModified, 
            T.Deleted AS Faqs_Deleted, 
            True AS _from0
        FROM AgrishareEntities.Faqs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Faqs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView25()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Faqs", @"
    SELECT VALUE -- Constructing Faqs
        [AgrishareModel.Faq](T1.Faq_Id, T1.Faq_Question, T1.Faq_Answer, T1.Faq_SortOrder, T1.Faq_DateCreated, T1.Faq_LastModified, T1.Faq_Deleted)
    FROM (
        SELECT 
            T.Id AS Faq_Id, 
            T.Question AS Faq_Question, 
            T.Answer AS Faq_Answer, 
            T.SortOrder AS Faq_SortOrder, 
            T.DateCreated AS Faq_DateCreated, 
            T.LastModified AS Faq_LastModified, 
            T.Deleted AS Faq_Deleted, 
            True AS _from0
        FROM AgrishareModelStoreContainer.Faqs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Log
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView26()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Log", @"
    SELECT VALUE -- Constructing Log
        [AgrishareModel.Store.Log](T1.Log_Id, T1.Log_User, T1.Log_Title, T1.Log_Description, T1.Log_LevelId, T1.Log_DateCreated, T1.Log_LastModified, T1.Log_Deleted)
    FROM (
        SELECT 
            T.Id AS Log_Id, 
            T.User AS Log_User, 
            T.Title AS Log_Title, 
            T.Description AS Log_Description, 
            CAST(T.LevelId AS [Edm.Int16]) AS Log_LevelId, 
            T.DateCreated AS Log_DateCreated, 
            T.LastModified AS Log_LastModified, 
            T.Deleted AS Log_Deleted, 
            True AS _from0
        FROM AgrishareEntities.Logs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Logs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView27()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Logs", @"
    SELECT VALUE -- Constructing Logs
        [AgrishareModel.Log](T1.Log_Id, T1.Log_User, T1.Log_Title, T1.Log_Description, T1.Log_LevelId, T1.Log_DateCreated, T1.Log_LastModified, T1.Log_Deleted)
    FROM (
        SELECT 
            T.Id AS Log_Id, 
            T.User AS Log_User, 
            T.Title AS Log_Title, 
            T.Description AS Log_Description, 
            CAST(T.LevelId AS [AgrishareModel.LogLevel]) AS Log_LevelId, 
            T.DateCreated AS Log_DateCreated, 
            T.LastModified AS Log_LastModified, 
            T.Deleted AS Log_Deleted, 
            True AS _from0
        FROM AgrishareModelStoreContainer.Log AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Pages
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView28()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Pages", @"
    SELECT VALUE -- Constructing Pages
        [AgrishareModel.Store.Pages](T1.Pages_Id, T1.Pages_ParentId, T1.Pages_TypeId, T1.Pages_Title, T1.Pages_Description, T1.Pages_Content, T1.Pages_Icon, T1.Pages_UrlPath, T1.Pages_Greedy, T1.Pages_TemplatePath, T1.Pages_ShowInMenu, T1.Pages_SortOrder, T1.Pages_DateCreated, T1.Pages_LastModified, T1.Pages_Deleted)
    FROM (
        SELECT 
            T.Id AS Pages_Id, 
            T.ParentId AS Pages_ParentId, 
            T.TypeId AS Pages_TypeId, 
            T.Title AS Pages_Title, 
            T.Description AS Pages_Description, 
            T.Content AS Pages_Content, 
            T.Icon AS Pages_Icon, 
            T.UrlPath AS Pages_UrlPath, 
            T.Greedy AS Pages_Greedy, 
            T.TemplatePath AS Pages_TemplatePath, 
            T.ShowInMenu AS Pages_ShowInMenu, 
            T.SortOrder AS Pages_SortOrder, 
            T.DateCreated AS Pages_DateCreated, 
            T.LastModified AS Pages_LastModified, 
            T.Deleted AS Pages_Deleted, 
            True AS _from0
        FROM AgrishareEntities.Pages AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Pages
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView29()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Pages", @"
    SELECT VALUE -- Constructing Pages
        [AgrishareModel.Page](T1.Page_Id, T1.Page_ParentId, T1.Page_TypeId, T1.Page_Title, T1.Page_Description, T1.Page_Content, T1.Page_Icon, T1.Page_UrlPath, T1.Page_Greedy, T1.Page_TemplatePath, T1.Page_ShowInMenu, T1.Page_SortOrder, T1.Page_DateCreated, T1.Page_LastModified, T1.Page_Deleted)
    FROM (
        SELECT 
            T.Id AS Page_Id, 
            T.ParentId AS Page_ParentId, 
            T.TypeId AS Page_TypeId, 
            T.Title AS Page_Title, 
            T.Description AS Page_Description, 
            T.Content AS Page_Content, 
            T.Icon AS Page_Icon, 
            T.UrlPath AS Page_UrlPath, 
            T.Greedy AS Page_Greedy, 
            T.TemplatePath AS Page_TemplatePath, 
            T.ShowInMenu AS Page_ShowInMenu, 
            T.SortOrder AS Page_SortOrder, 
            T.DateCreated AS Page_DateCreated, 
            T.LastModified AS Page_LastModified, 
            T.Deleted AS Page_Deleted, 
            True AS _from0
        FROM AgrishareModelStoreContainer.Pages AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareModelStoreContainer.Templates
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView30()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareModelStoreContainer.Templates", @"
    SELECT VALUE -- Constructing Templates
        [AgrishareModel.Store.Templates](T1.Templates_Id, T1.Templates_TypeId, T1.Templates_Title, T1.Templates_HTML, T1.Templates_DateCreated, T1.Templates_LastModified, T1.Templates_Deleted)
    FROM (
        SELECT 
            T.Id AS Templates_Id, 
            CAST(T.TypeId AS [Edm.Int16]) AS Templates_TypeId, 
            T.Title AS Templates_Title, 
            T.HTML AS Templates_HTML, 
            T.DateCreated AS Templates_DateCreated, 
            T.LastModified AS Templates_LastModified, 
            T.Deleted AS Templates_Deleted, 
            True AS _from0
        FROM AgrishareEntities.Templates AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for AgrishareEntities.Templates
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView31()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("AgrishareEntities.Templates", @"
    SELECT VALUE -- Constructing Templates
        [AgrishareModel.Template](T1.Template_Id, T1.Template_TypeId, T1.Template_Title, T1.Template_HTML, T1.Template_DateCreated, T1.Template_LastModified, T1.Template_Deleted)
    FROM (
        SELECT 
            T.Id AS Template_Id, 
            CAST(T.TypeId AS [AgrishareModel.TemplateType]) AS Template_TypeId, 
            T.Title AS Template_Title, 
            T.HTML AS Template_HTML, 
            T.DateCreated AS Template_DateCreated, 
            T.LastModified AS Template_LastModified, 
            T.Deleted AS Template_Deleted, 
            True AS _from0
        FROM AgrishareModelStoreContainer.Templates AS T
    ) AS T1");
        }
    }
}
