//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrishare.Core.Entities
{
    using System;
    
    public enum BookingStatus : short
    {
        Pending = 0,
        Approved = 1,
        Declined = 2,
        InProgress = 3,
        Complete = 4,
        None = -1
    }
}
