//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrishare.Core.Entities
{
    using System;
    
    public enum JournalType : short
    {
        None = 0,
        Payment = 1,
        Refund = 2,
        Settlement = 3,
        Fee = 4
    }
}
