//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrishare.Core.Entities
{
    using System;
    
    public enum Language : short
    {
        English = 1,
        Shona = 2,
        Ndebele = 3,
        Luganda = 4,
        Chichewa = 5,
        Acholi = 6,
        Ateso = 7,
        Lango = 8,
        Runyankore = 9,
        Runyoro = 10,
        Swahili = 11
    }
}
