//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrishare.Core.Entities
{
    using System;
    
    public enum ListingCondition : short
    {
        None = 0,
        VeryGood = 1,
        Good = 2,
        Fair = 3,
        Poor = 4,
        VeryPoor = 5
    }
}
