//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrishare.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public MessageStatus StatusId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool Deleted { get; set; }
        public int ReplyCount { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string Telephone { get; set; }
        public string GUID { get; set; }
    
        public virtual User User { get; set; }
    }
}
