//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrishare.Core.Entities
{
    using System;
    
    public enum NotificationType : short
    {
        None = 0,
        NewBooking = 1,
        BookingConfirmed = 2,
        BookingCancelled = 3,
        ServiceComplete = 4,
        NewReview = 5,
        PaymentReceived = 6
    }
}
