//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrishare.Core.Entities
{
    using System;
    
    public enum PaymentGateway : short
    {
        None = 0,
        EcoCashZimbabwe = 1,
        AirtelUganda = 2,
        MTNUganda = 3
    }
}
