//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrishare.Core.Entities
{
    using System;
    
    public enum QuantityUnit : short
    {
        None = 0,
        Hectares = 1,
        Bags = 2,
        Days = 3,
        Years = 4,
        Acres = 5
    }
}
