//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrishare.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public int ListingId { get; set; }
        public int UserId { get; set; }
        public string Comments { get; set; }
        public decimal Stars { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool Deleted { get; set; }
        public int BookingId { get; set; }
    
        public virtual Listing Listing { get; set; }
        public virtual User User { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
