//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrishare.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public int ListingId { get; set; }
        public int CategoryId { get; set; }
        public bool Mobile { get; set; }
        public decimal TotalVolume { get; set; }
        public QuantityUnit QuantityUnitId { get; set; }
        public TimeUnit TimeUnitId { get; set; }
        public DistanceUnit DistanceUnitId { get; set; }
        public decimal MinimumQuantity { get; set; }
        public decimal MaximumDistance { get; set; }
        public decimal PricePerQuantityUnit { get; set; }
        public decimal FuelPerQuantityUnit { get; set; }
        public decimal TimePerQuantityUnit { get; set; }
        public decimal PricePerDistanceUnit { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
