//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrishare.Core.Entities
{
    using System;
    
    public enum TransactionStatus : short
    {
        None = 0,
        Cancelled = 1,
        CreatedNotPaid = 2,
        AwaitingRedirect = 3,
        Paid = 4,
        Failed = 5,
        Initiated = 6,
        Processing = 7,
        Refunded = 8,
        Refused = 9,
        Denied = 10,
        PendingSubscriberValidation = 11,
        Deleted = 12,
        Pending = 13,
        Error = 99
    }
}
