//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrishare.Core.Entities
{
    using System;
    
    public enum TransactionStatus : short
    {
        None = 0,
        Completed = 4,
        Failed = 5,
        Refunded = 8,
        PendingSubscriberValidation = 11,
        Pending = 13,
        Error = 99,
        TransactionTimedout = 9
    }
}
