//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrishare.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Journals = new HashSet<Journal>();
            this.Messages = new HashSet<Message>();
            this.BookingComments = new HashSet<BookingComment>();
            this.UserVouchers = new HashSet<UserVoucher>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string Telephone { get; set; }
        public Gender GenderId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public short NotificationPreferences { get; set; }
        public Interest InterestId { get; set; }
        public string RoleList { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string AuthToken { get; set; }
        public int FailedLoginAttempts { get; set; }
        public string VerificationCode { get; set; }
        public Nullable<System.DateTime> VerificationCodeExpiry { get; set; }
        public string SignalRConnectionId { get; set; }
        public UserStatus StatusId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool Deleted { get; set; }
        public Language LanguageId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public AgentUserType AgentTypeId { get; set; }
        public short PaymentMethod { get; set; }
        public string EncryptedBankAccountJson { get; set; }
        public int RegionId { get; set; }
        public int FailedVoucherAttempts { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string AgentName { get; set; }
        public Nullable<int> ReferredById { get; set; }
        public int ReferralCount { get; set; }
        public string ReferralCode { get; set; }
        public int FailedOtpAttempts { get; set; }
        public int OtpRequests { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journal> Journals { get; set; }
        public virtual Agent Agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingComment> BookingComments { get; set; }
        public virtual Region Region { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserVoucher> UserVouchers { get; set; }
    }
}
